#ifndef INC_CONSTANTS_MQH
#define INC_CONSTANTS_MQH

#define EA_VERSION "XAUUSD-GOD 1.0"
#define SYMBOL_TARGET "XAUUSD"
#define TF_TARGET PERIOD_M5

const long MAGIC_BASE = 66050001;

#define REASON_LIQ_SWEEP "LIQ_SWEEP"
#define REASON_TREND_BO  "TREND_BO"

const int MIN_SL_POINTS = 10;
const int MIN_TP_POINTS = 10;

#endif // INC_CONSTANTS_MQH